#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"

export GOSS_PATH=${DIR}/../goss-linux-amd64
export GOSS_FILES_PATH=${DIR}

RETURN=0

printf "\n\033[36mTEST\033[0m [Default]\n\n"

export GOSS_VARS=vars.default.yaml

${DIR}/../dgoss run \
    ardeveloppement/system \
    || ((RETURN++))

printf "\n\033[36mTEST\033[0m [Default - Php 7.1]\n\n"

export GOSS_VARS=vars.default.7.1.yaml

${DIR}/../dgoss run \
    --env PHP_VERSION=7.1 \
    ardeveloppement/system \
    || ((RETURN++))

printf "\n\033[36mTEST\033[0m [Default - Php 7.2]\n\n"

export GOSS_VARS=vars.default.7.2.yaml

${DIR}/../dgoss run \
    --env PHP_VERSION=7.2 \
    ardeveloppement/system \
    || ((RETURN++))

printf "\n\033[36mTEST\033[0m [Default - Php 7.3]\n\n"

export GOSS_VARS=vars.default.7.3.yaml

${DIR}/../dgoss run \
    --env PHP_VERSION=7.3 \
    ardeveloppement/system \
    || ((RETURN++))

printf "\n\033[36mTEST\033[0m [Default - Php 7.4]\n\n"

export GOSS_VARS=vars.default.yaml

${DIR}/../dgoss run \
    --env PHP_VERSION=7.4 \
    ardeveloppement/system \
    || ((RETURN++))

printf "\n\033[36mTEST\033[0m [Custom]\n\n"

export GOSS_VARS=vars.yaml

${DIR}/../dgoss run \
    --env PHP_MODULES_EXTRA="mysqlnd pdo_mysql pdo_pgsql amqp" \
    ardeveloppement/system \
    || ((RETURN++))

printf "\n\033[36mTEST\033[0m [Custom - Php 7.1]\n\n"

${DIR}/../dgoss run \
    --env PHP_MODULES_EXTRA="mysqlnd pdo_mysql pdo_pgsql amqp" \
    --env PHP_VERSION=7.1 \
    ardeveloppement/system \
    || ((RETURN++))

printf "\n\033[36mTEST\033[0m [Custom - Php 7.2]\n\n"

${DIR}/../dgoss run \
    --env PHP_MODULES_EXTRA="mysqlnd pdo_mysql pdo_pgsql amqp" \
    --env PHP_VERSION=7.2 \
    ardeveloppement/system \
    || ((RETURN++))

printf "\n\033[36mTEST\033[0m [Custom - Php 7.3]\n\n"

${DIR}/../dgoss run \
    --env PHP_MODULES_EXTRA="mysqlnd pdo_mysql pdo_pgsql amqp" \
    --env PHP_VERSION=7.3 \
    ardeveloppement/system \
    || ((RETURN++))

printf "\n\033[36mTEST\033[0m [Custom - Php 7.4]\n\n"

${DIR}/../dgoss run \
    --env PHP_MODULES_EXTRA="mysqlnd pdo_mysql pdo_pgsql amqp" \
    --env PHP_VERSION=7.4 \
    ardeveloppement/system \
    || ((RETURN++))

exit ${RETURN}
