#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"

export GOSS_PATH=${DIR}/../goss-linux-amd64
export GOSS_FILES_PATH=${DIR}

RETURN=0

printf "\n\033[36mTEST\033[0m [Default]\n\n"

export GOSS_VARS=vars.default.yaml

${DIR}/../dgoss run \
    --env APP=php \
    ardeveloppement/system \
    || ((RETURN++))

printf "\n\033[36mTEST\033[0m [Default - Php 7.1]\n\n"

${DIR}/../dgoss run \
    --env PHP_VERSION=7.1 \
    --env APP=php \
    ardeveloppement/system \
    || ((RETURN++))

printf "\n\033[36mTEST\033[0m [Default - Php 7.2]\n\n"

${DIR}/../dgoss run \
    --env PHP_VERSION=7.2 \
    --env APP=php \
    ardeveloppement/system \
    || ((RETURN++))

printf "\n\033[36mTEST\033[0m [Default - Php 7.3]\n\n"

${DIR}/../dgoss run \
    --env PHP_VERSION=7.3 \
    --env APP=php \
    ardeveloppement/system \
    || ((RETURN++))

printf "\n\033[36mTEST\033[0m [Default - Php 7.4]\n\n"

${DIR}/../dgoss run \
    --env PHP_VERSION=7.4 \
    --env APP=php \
    ardeveloppement/system \
    || ((RETURN++))

printf "\n\033[36mTEST\033[0m [Custom]\n\n"

export GOSS_VARS=vars.yaml

${DIR}/../dgoss run \
    --env PHP_FPM_POOL_PM_MAX_CHILDREN=6 \
    --env PHP_FPM_POOL_PM_START_SERVERS=3 \
    --env PHP_FPM_POOL_PM_MIN_SPARE_SERVERS=2 \
    --env PHP_FPM_POOL_PM_MAX_SPARE_SERVERS=4 \
    --env APP=php \
    ardeveloppement/system \
    || ((RETURN++))

printf "\n\033[36mTEST\033[0m [Custom - Php 7.1]\n\n"

${DIR}/../dgoss run \
    --env PHP_FPM_POOL_PM_MAX_CHILDREN=6 \
    --env PHP_FPM_POOL_PM_START_SERVERS=3 \
    --env PHP_FPM_POOL_PM_MIN_SPARE_SERVERS=2 \
    --env PHP_FPM_POOL_PM_MAX_SPARE_SERVERS=4 \
    --env PHP_VERSION=7.1 \
    --env APP=php \
    ardeveloppement/system \
    || ((RETURN++))

printf "\n\033[36mTEST\033[0m [Custom - Php 7.2]\n\n"

${DIR}/../dgoss run \
    --env PHP_FPM_POOL_PM_MAX_CHILDREN=6 \
    --env PHP_FPM_POOL_PM_START_SERVERS=3 \
    --env PHP_FPM_POOL_PM_MIN_SPARE_SERVERS=2 \
    --env PHP_FPM_POOL_PM_MAX_SPARE_SERVERS=4 \
    --env PHP_VERSION=7.2 \
    --env APP=php \
    ardeveloppement/system \
    || ((RETURN++))

printf "\n\033[36mTEST\033[0m [Custom - Php 7.3]\n\n"

${DIR}/../dgoss run \
    --env PHP_FPM_POOL_PM_MAX_CHILDREN=6 \
    --env PHP_FPM_POOL_PM_START_SERVERS=3 \
    --env PHP_FPM_POOL_PM_MIN_SPARE_SERVERS=2 \
    --env PHP_FPM_POOL_PM_MAX_SPARE_SERVERS=4 \
    --env PHP_VERSION=7.3 \
    --env APP=php \
    ardeveloppement/system \
    || ((RETURN++))

printf "\n\033[36mTEST\033[0m [Custom - Php 7.4]\n\n"

${DIR}/../dgoss run \
    --env PHP_FPM_POOL_PM_MAX_CHILDREN=6 \
    --env PHP_FPM_POOL_PM_START_SERVERS=3 \
    --env PHP_FPM_POOL_PM_MIN_SPARE_SERVERS=2 \
    --env PHP_FPM_POOL_PM_MAX_SPARE_SERVERS=4 \
    --env PHP_VERSION=7.4 \
    --env APP=php \
    ardeveloppement/system \
    || ((RETURN++))

exit ${RETURN}
