#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"

export GOSS_PATH=${DIR}/../goss-linux-amd64
export GOSS_FILES_PATH=${DIR}

RETURN=0

printf "\n\033[36mTEST\033[0m [Default]\n\n"

export GOSS_VARS=vars.default.yaml

${DIR}/../dgoss run \
    ardeveloppement/system \
    || ((RETURN++))

printf "\n\033[36mTEST\033[0m [7.2]\n\n"

export GOSS_VARS=vars.7.2.yaml

${DIR}/../dgoss run \
    --env PHP_VERSION=7.2 \
    ardeveloppement/system \
    || ((RETURN++))

printf "\n\033[36mTEST\033[0m [7.3]\n\n"

export GOSS_VARS=vars.7.3.yaml

${DIR}/../dgoss run \
    --env PHP_VERSION=7.3 \
    ardeveloppement/system \
    || ((RETURN++))

exit ${RETURN}
