#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"

export GOSS_PATH=${DIR}/../goss-linux-amd64
export GOSS_FILES_PATH=${DIR}

${DIR}/../dgoss edit \
    ardeveloppement/system
