#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"

export GOSS_PATH=${DIR}/../goss-linux-amd64
export GOSS_FILES_PATH=${DIR}

RETURN=0

printf "\n\033[36mTEST\033[0m [Default]\n\n"

export GOSS_VARS=vars.default.yaml

${DIR}/../dgoss run \
    ardeveloppement/system \
    || ((RETURN++))

printf "\n\033[36mTEST\033[0m [Custom]\n\n"

export GOSS_VARS=vars.yaml

${DIR}/../dgoss run \
    --env NGINX_DIRECTIVES="[\"gzip\", \"error\"]" \
    ardeveloppement/system \
    || ((RETURN++))

exit ${RETURN}
