#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"

export GOSS_PATH=${DIR}/../goss-linux-amd64
export GOSS_FILES_PATH=${DIR}

RETURN=0

printf "\n\033[36mTEST\033[0m [Default]\n\n"

export GOSS_VARS=vars.default.yaml

${DIR}/../dgoss run \
    ardeveloppement/system \
    sleep infinity \
    || ((RETURN++))

printf "\n\033[36mTEST\033[0m [Default - Php 7.1]\n\n"

${DIR}/../dgoss run \
    --env PHP_VERSION=7.1 \
    ardeveloppement/system \
    sleep infinity \
    || ((RETURN++))

printf "\n\033[36mTEST\033[0m [Default - Php 7.2]\n\n"

${DIR}/../dgoss run \
    --env PHP_VERSION=7.2 \
    ardeveloppement/system \
    sleep infinity \
    || ((RETURN++))

printf "\n\033[36mTEST\033[0m [Custom]\n\n"

export GOSS_VARS=vars.yaml

${DIR}/../dgoss run \
    --env PHP_DATE_TIMEZONE=Europe/Paris \
    ardeveloppement/system \
    sleep infinity \
    || ((RETURN++))

${DIR}/../dgoss run \
    --env PHP_CLI_DATE_TIMEZONE=Europe/Paris \
    ardeveloppement/system \
    sleep infinity \
    || ((RETURN++))

printf "\n\033[36mTEST\033[0m [Custom - Php 7.1]\n\n"

${DIR}/../dgoss run \
    --env PHP_DATE_TIMEZONE=Europe/Paris \
    --env PHP_VERSION=7.1 \
    ardeveloppement/system \
    sleep infinity \
    || ((RETURN++))

${DIR}/../dgoss run \
    --env PHP_CLI_DATE_TIMEZONE=Europe/Paris \
    --env PHP_VERSION=7.1 \
    ardeveloppement/system \
    sleep infinity \
    || ((RETURN++))

printf "\n\033[36mTEST\033[0m [Custom - Php 7.2]\n\n"

${DIR}/../dgoss run \
    --env PHP_DATE_TIMEZONE=Europe/Paris \
    --env PHP_VERSION=7.2 \
    ardeveloppement/system \
    sleep infinity \
    || ((RETURN++))

${DIR}/../dgoss run \
    --env PHP_CLI_DATE_TIMEZONE=Europe/Paris \
    --env PHP_VERSION=7.2 \
    ardeveloppement/system \
    sleep infinity \
    || ((RETURN++))

exit ${RETURN}
