#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"

export GOSS_PATH=${DIR}/../goss-linux-amd64
export GOSS_FILES_PATH=${DIR}

RETURN=0

printf "\n\033[36mTEST\033[0m [Angular]\n\n"

export GOSS_VARS=vars.angular.yaml

${DIR}/../dgoss run \
    --mount type=bind,source=${DIR}/fixtures/angular,target=/srv/app \
    ardeveloppement/system \
    supervisord --configuration /etc/supervisor/app/angular.conf \
    || ((RETURN++))

printf "\n\033[36mTEST\033[0m [Html]\n\n"

export GOSS_VARS=vars.html.yaml

${DIR}/../dgoss run \
    --mount type=bind,source=${DIR}/fixtures/html,target=/srv/app \
    ardeveloppement/system \
    supervisord --configuration /etc/supervisor/app/html.conf \
    || ((RETURN++))

printf "\n\033[36mTEST\033[0m [Php]\n\n"

export GOSS_VARS=vars.php.yaml

${DIR}/../dgoss run \
    --mount type=bind,source=${DIR}/fixtures/php,target=/srv/app \
    ardeveloppement/system \
    supervisord --configuration /etc/supervisor/app/php.conf \
    || ((RETURN++))

printf "\n\033[36mTEST\033[0m [Silex]\n\n"

export GOSS_VARS=vars.silex.yaml

${DIR}/../dgoss run \
    --mount type=bind,source=${DIR}/fixtures/silex,target=/srv/app \
    ardeveloppement/system \
    supervisord --configuration /etc/supervisor/app/silex.conf \
    || ((RETURN++))

printf "\n\033[36mTEST\033[0m [Symfony 2]\n\n"

export GOSS_VARS=vars.symfony_2.yaml

${DIR}/../dgoss run \
    --mount type=bind,source=${DIR}/fixtures/symfony_2,target=/srv/app \
    ardeveloppement/system \
    supervisord --configuration /etc/supervisor/app/symfony_2.conf \
    || ((RETURN++))

printf "\n\033[36mTEST\033[0m [Symfony 4]\n\n"

export GOSS_VARS=vars.symfony_4.yaml

${DIR}/../dgoss run \
    --mount type=bind,source=${DIR}/fixtures/symfony_4,target=/srv/app \
    ardeveloppement/system \
    supervisord --configuration /etc/supervisor/app/symfony_4.conf \
    || ((RETURN++))

printf "\n\033[36mTEST\033[0m [Vue.js]\n\n"

export GOSS_VARS=vars.vuejs.yaml

${DIR}/../dgoss run \
    --mount type=bind,source=${DIR}/fixtures/vuejs,target=/srv/app \
    ardeveloppement/system \
    supervisord --configuration /etc/supervisor/app/vuejs.conf \
    || ((RETURN++))

exit ${RETURN}
